apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cns-quote-service
spec:
  template:
    spec:
      containers:
        - name: cns-quote-service
          image: ghcr.io/akfnt/cns-quote-service
          ports:
            - containerPort: 9101
          resources:
            requests:
              cpu: '0.1'
              memory: '128Mi'
            limits:
              cpu: '2'
              memory: '512Mi'